title: Soda Documentation
email: support@soda.io
description: >- # this means to ignore newlines until "baseurl:"
  Learn how to use Soda to test and monitor data quality.
baseurl: ""
url: ""
twitter_username: sodadata
github_username:  sodadata

# Build settings minima
theme: just-the-docs
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-last-modified-at

logo: /assets/images/soda-logo.svg
color_scheme: soda

aux_links:
  "Soda SQL on GitHub":
    - "//github.com/sodadata/soda-sql"